"""Fix FK to session_id in SharedData

Revision ID: 0b9d5d4245f4
Revises: 80d803a400ab
Create Date: 2025-05-13 23:47:34.685766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9d5d4245f4'
down_revision = '80d803a400ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content3', sa.String(length=100), nullable=True))
        batch_op.drop_column('shared_content1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content1', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('shared_content3')

    # ### end Alembic commands ###
