"""Add google_id to User model

Revision ID: 208058c3b0a5
Revises: df2182f60bbd
Create Date: 2025-05-05 18:21:26.471648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208058c3b0a5'
down_revision = 'df2182f60bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
