"""Fix FK to session_id in SharedData

Revision ID: 3f239600a7ca
Revises: 8bd45417ef58
Create Date: 2025-05-13 22:30:42.101566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f239600a7ca'
down_revision = '8bd45417ef58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content3', sa.String(length=100), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'accepted'),
               existing_nullable=True)
        batch_op.create_index('idx_shared_data_session_id', ['session_id'], unique=False)
        batch_op.create_index('idx_shared_data_shared_by_user_id', ['shared_by_user_id'], unique=False)
        batch_op.create_index('idx_shared_data_shared_with_user_id', ['shared_with_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.drop_index('idx_shared_data_shared_with_user_id')
        batch_op.drop_index('idx_shared_data_shared_by_user_id')
        batch_op.drop_index('idx_shared_data_session_id')
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'accepted'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('shared_content3')

    # ### end Alembic commands ###
