"""Fix FK to session_id in SharedData

Revision ID: 3fd91839f6d6
Revises: 0b9d5d4245f4
Create Date: 2025-05-14 15:50:49.093621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd91839f6d6'
down_revision = '0b9d5d4245f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_records',
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False)
    )
    # ### end Alembic commands ###
