"""Fix FK to session_id in SharedData

Revision ID: 80d803a400ab
Revises: ef9157e2b344
Create Date: 2025-05-13 23:44:51.785207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d803a400ab'
down_revision = 'ef9157e2b344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content1', sa.String(length=100), nullable=True))
        batch_op.drop_column('shared_content3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content3', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('shared_content1')

    # ### end Alembic commands ###
