"""create shared_data table

Revision ID: 8bd45417ef58
Revises: cd9edb9256a2
Create Date: 2025-05-13 11:29:55.471083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd45417ef58'
down_revision = 'cd9edb9256a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_content', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('shared_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_data')
    # ### end Alembic commands ###
