"""Fix FK to session_id in SharedData

Revision ID: baa0ceeabdd7
Revises: 3f239600a7ca
Create Date: 2025-05-13 23:40:41.639701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa0ceeabdd7'
down_revision = '3f239600a7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content1', sa.String(length=100), nullable=True))
        batch_op.drop_column('shared_content3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content3', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('shared_content1')

    # ### end Alembic commands ###
