"""empty message

Revision ID: df881c01a206
Revises: 8bb930ce1cf9
Create Date: 2025-05-16 23:20:58.764672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df881c01a206'
down_revision = '8bb930ce1cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streak_freeze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('used_on', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('reflection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('productivity_rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('shared_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_content', sa.Integer(), nullable=True),
    sa.Column('shared_content3', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted'), nullable=True),
    sa.Column('shared_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], name='fk_shared_data_session_id'),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.create_index('idx_shared_data_session_id', ['session_id'], unique=False)
        batch_op.create_index('idx_shared_data_shared_by_user_id', ['shared_by_user_id'], unique=False)
        batch_op.create_index('idx_shared_data_shared_with_user_id', ['shared_with_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.drop_index('idx_shared_data_shared_with_user_id')
        batch_op.drop_index('idx_shared_data_shared_by_user_id')
        batch_op.drop_index('idx_shared_data_session_id')

    op.drop_table('shared_data')
    op.drop_table('session')
    op.drop_table('reflection')
    op.drop_table('friends')
    op.drop_table('user')
    op.drop_table('streak_freeze')
    # ### end Alembic commands ###
