"""Fix FK to session_id in SharedData

Revision ID: ef9157e2b344
Revises: baa0ceeabdd7
Create Date: 2025-05-13 23:42:16.635743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9157e2b344'
down_revision = 'baa0ceeabdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content3', sa.String(length=100), nullable=True))
        batch_op.drop_column('shared_content1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content1', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('shared_content3')

    # ### end Alembic commands ###
